platform :osx, '10.11'
use_frameworks!

target 'SearchBox_Example' do
  pod 'SearchBox', :path => '../'
  pod 'Alamofire', '~> 4.6'
  pod 'PromiseKit', '~> 6.0'
  pod 'PromiseKit/Alamofire', '~> 6.0'
  pod 'SwiftyBeaver', '~> 1.5'

  target 'SearchBox_Tests' do
    inherit! :search_paths

    
  end
end
