disabled_rules:
  - function_body_length
  - line_length
  - file_length
  - trailing_whitespace
  - identifier_name
  - force_cast
  - force_try
  - cyclomatic_complexity
  - type_body_length
  - nesting
    
